OPENAI_API_KEY = "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"
ELEVEN_API_KEY = "sk_b7ecdb37e78400338be64d4645fcfc0e02a1fa66fc7aa0d4"
VOICE_ID = "ZthaVUMqkZAMI751u7Km"
